version: '3.8'

services:
  # 主应用服务
  slavopolis-docs:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: slavopolis-docs
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai
    networks:
      - slavopolis-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.slavopolis-docs.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.slavopolis-docs.entrypoints=websecure"
      - "traefik.http.routers.slavopolis-docs.tls.certresolver=letsencrypt"

  # Traefik反向代理（可选）
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik仪表板
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - ./traefik/acme:/acme
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=admin@your-domain.com
      - --certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json
      - --log.level=INFO
    networks:
      - slavopolis-network
    profiles:
      - traefik

  # Watchtower自动更新（可选）
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600  # 每小时检查一次
      - WATCHTOWER_INCLUDE_STOPPED=true
    networks:
      - slavopolis-network
    profiles:
      - watchtower

  # Prometheus监控（可选）
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - slavopolis-network
    profiles:
      - monitoring

  # Grafana仪表板（可选）
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - slavopolis-network
    profiles:
      - monitoring

networks:
  slavopolis-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: 